### ISSUE TITLE
Vault with ACA

### ISSUE THREAD

**Issue by baoj-dfo** [Neutrollized/hashicorp-vault-with-aci#1]
@Neutrollized  expecting an example for hosting vault in Azure Container App from you :)

**Comment by Neutrollized** [comment]
Yeah!  Thanks for reminding me.  That's been on my list for a while, but just forgot.  Shouldn't be too difficult, I'll try to get something put together this weekend.

**Comment by baoj-dfo** [comment]
@Neutrollized  Thanks for the quick reply.

**Comment by Neutrollized** [comment]
Here you go: https://github.com/Neutrollized/hashicorp-vault-with-aca
